let getData = {
  data: [
    {
      Owner: {
        name: "Tobias Müller",
        id: "618394000001298026",
        email: "tobias.mueller@lm-finance.ch",
      },
      Punktewert_Kalk: 5.64,
      $currency_symbol: "CHF",
      Punktestufe: 45,
      $field_states: null,
      K_ndigungsfrist: "3 Monate",
      Gek_ndigt_per: null,
      Last_Activity_Time: "2025-07-08T17:14:22+02:00",
      Mitarbeiter_Faktor: 1,
      $state: "save",
      $process_flow: false,
      Deal_Name: "test bctl multiconcept",
      Test: null,
      Verrechnet: false,
      Punktewert1: 5.64,
      Stage: "In Kraft",
      Formel_8: "2027-06-01",
      $locked_for_me: false,
      id: "618394000017775181",
      Faktor: 100,
      Ablaufdatum: null,
      $approved: true,
      Alter_dieses_Jahr: 45,
      Ablaufdatum_VVG: null,
      $approval: {
        delegate: false,
        takeover: false,
        approve: false,
        reject: false,
        recall: false,
        resubmit: false,
      },
      K_ndbar_auf: null,
      Storno_abgerechnet: false,
      $editable: true,
      Stornobetrag: null,
      Beginndatum: "2025-06-01",
      Storniert_am: null,
      Contact_Email: null,
      Provision_ausbezahlt: 215.55,
      $status: "cmv_1-1",
      Sysnum: "V-10237",
      Punkte: 0,
      Mitarbeiter: {
        module: "CustomModule3",
        name: "Tobias Müller",
        id: "618394000001304171",
      },
      $zia_owner_assignment: "owner_recommendation_unavailable",
      updated: true,
      Provision_erhalten_am: "2025-06-23",
      Weitere_Gr_nde: null,
      Z_Elite: false,
      Description: null,
      Delete_Attachments: true,
      Zusatz_Mitarbeiter: 0,
      $photo_id: null,
      Erwartete_Provision: null,
      Firma: null,
      $review_process: {
        approve: false,
        reject: false,
        resubmit: false,
      },
      Annahmedatum: "2025-05-23",
      $layout_id: {
        display_label: "Standard",
        name: "Standard",
        id: "618394000000032043",
      },
      Stornogrund: null,
      Closing_Date: "2025-05-01",
      WD_Test:
        "https://workdrive.zohopublic.eu/external/8c58f7a1605f960937aa78bc5285f7c4707ca343bab3a6724bc1b8790cd29a1f",
      Alte_Combinvest_File_ID: null,
      $review: null,
      Lead_Conversion_Time: null,
      Provisionen: {
        module: "CustomModule7",
        name: "Zugerberg Finanz (Freie Vorsorge 3b)",
        id: "618394000017005001",
      },
      Erhaltene_Provision: null,
      Overall_Sales_Duration: 0,
      Gesellschaft: {
        module: "Vendors",
        name: "Zugerberg Finanz AG",
        id: "618394000000422985",
      },
      Versicherungsart: null,
      Account_Name: null,
      Provision_inkl_Storno: 253.8,
      Gesellschaftsname: "Zugerberg Finanz AG",
      Eingangsdatum: "2025-05-02",
      Ablaufdatum_KVG: null,
      Pr_mie_nach_Vertrag_Faktor_x6: null,
      Pr_mie_Basiswerte: "Nettopremie",
      $orchestration: false,
      Contact_Name: {
        name: "Ferat Ademi",
        id: "618394000013870001",
      },
      Pipeline: "Antrag",
      Laufzeit: null,
      Sales_Cycle_Duration: 0,
      Type: "Freizügigkeit",
      Pr_mie_Provision: 564,
      Punkte_KVG: null,
      Tippgeber_Besitzer: null,
      $in_merge: false,
      Stornowert: 0.85,
      Stornowert_in_CHF: 38.25,
      J_hrliches_K_ndigungsrecht: false,
      Locked__s: false,
      Tag: [],
      easyworkdriveforcrm__Workdrive_Folder_ID_EXT:
        "5gdgxa8ba2358596042299ed0ab575a680a17",
      $approval_state: "approved",
    },
  ],
  $responseHeaders: {
    "x-ratelimit-remaining": null,
    "x-ratelimit-limit": null,
    "x-ratelimit-reset": null,
  },
};
let kk = getData?.data[0].Gesellschaft?.name;
console.log(kk);
